version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always